In [1]:
import pandas as pd

In [2]:
import pandas as pd

dataset = pd.read_csv(
    r"D:\basic python\sentiment Analaysis\group.txt",
    header=None,
    on_bad_lines='skip',
    encoding='utf-8'
)

In [3]:
dataset

             0                                                  1
0     14/07/19   12:50 pm - Messages to this group are now sec...
1     06/02/17   10:44 pm - Mama created group "Happy birthday...
2     14/07/19                  12:50 pm - Jambo anna 1 added you
3     14/07/19   12:50 pm - Jambo anna 1 changed this group's ...
4     14/07/19                                12:51 pm - Mama: ♥❤
...        ...                                                ...
1385  15/12/19              11:08 pm - Meena Anni: Good night all
1386  15/12/19                     11:56 pm - AR❤: Good night all
1387  15/12/19             11:58 pm - Meena Anni: <Media omitted>
1388  17/12/19   6:52 pm - Jambo anna 1: Best servant of the y...
1389  17/12/19            6:52 pm - Jambo anna 1: <Media omitted>

[1390 rows x 2 columns]

In [4]:
df = dataset.drop(0)

In [5]:
 df

             0                                                  1
1     06/02/17   10:44 pm - Mama created group "Happy birthday...
2     14/07/19                  12:50 pm - Jambo anna 1 added you
3     14/07/19   12:50 pm - Jambo anna 1 changed this group's ...
4     14/07/19                                12:51 pm - Mama: ♥❤
5     14/07/19   12:53 pm - Jambo anna 1 changed the subject f...
...        ...                                                ...
1385  15/12/19              11:08 pm - Meena Anni: Good night all
1386  15/12/19                     11:56 pm - AR❤: Good night all
1387  15/12/19             11:58 pm - Meena Anni: <Media omitted>
1388  17/12/19   6:52 pm - Jambo anna 1: Best servant of the y...
1389  17/12/19            6:52 pm - Jambo anna 1: <Media omitted>

[1389 rows x 2 columns]

In [6]:
df.columns = ["Date", "Chat"]

In [7]:
df

          Date                                               Chat
1     06/02/17   10:44 pm - Mama created group "Happy birthday...
2     14/07/19                  12:50 pm - Jambo anna 1 added you
3     14/07/19   12:50 pm - Jambo anna 1 changed this group's ...
4     14/07/19                                12:51 pm - Mama: ♥❤
5     14/07/19   12:53 pm - Jambo anna 1 changed the subject f...
...        ...                                                ...
1385  15/12/19              11:08 pm - Meena Anni: Good night all
1386  15/12/19                     11:56 pm - AR❤: Good night all
1387  15/12/19             11:58 pm - Meena Anni: <Media omitted>
1388  17/12/19   6:52 pm - Jambo anna 1: Best servant of the y...
1389  17/12/19            6:52 pm - Jambo anna 1: <Media omitted>

[1389 rows x 2 columns]

In [8]:
Message = df["Chat"].str.split("-", n=1, expand = True)

In [9]:
Message

               0                                                  1
1      10:44 pm      Mama created group "Happy birthday jambu mama"
2      12:50 pm                              Jambo anna 1 added you
3      12:50 pm              Jambo anna 1 changed this group's icon
4      12:51 pm                                            Mama: ♥❤
5      12:53 pm    Jambo anna 1 changed the subject from "Happy ...
...          ...                                                ...
1385   11:08 pm                          Meena Anni: Good night all
1386   11:56 pm                                 AR❤: Good night all
1387   11:58 pm                         Meena Anni: <Media omitted>
1388    6:52 pm         Jambo anna 1: Best servant of the year 2019
1389    6:52 pm                       Jambo anna 1: <Media omitted>

[1389 rows x 2 columns]

In [10]:
df["Time"] = Message[0]

In [11]:
df

          Date                                               Chat        Time
1     06/02/17   10:44 pm - Mama created group "Happy birthday...   10:44 pm
2     14/07/19                  12:50 pm - Jambo anna 1 added you   12:50 pm
3     14/07/19   12:50 pm - Jambo anna 1 changed this group's ...   12:50 pm
4     14/07/19                                12:51 pm - Mama: ♥❤   12:51 pm
5     14/07/19   12:53 pm - Jambo anna 1 changed the subject f...   12:53 pm
...        ...                                                ...         ...
1385  15/12/19              11:08 pm - Meena Anni: Good night all   11:08 pm
1386  15/12/19                     11:56 pm - AR❤: Good night all   11:56 pm
1387  15/12/19             11:58 pm - Meena Anni: <Media omitted>   11:58 pm
1388  17/12/19   6:52 pm - Jambo anna 1: Best servant of the y...    6:52 pm
1389  17/12/19            6:52 pm - Jambo anna 1: <Media omitted>    6:52 pm

[1389 rows x 3 columns]

In [16]:
Message[1]

1          Mama created group "Happy birthday jambu mama"
2                                  Jambo anna 1 added you
3                  Jambo anna 1 changed this group's icon
4                                                Mama: ♥❤
5        Jambo anna 1 changed the subject from "Happy ...
                              ...
1385                           Meena Anni: Good night all
1386                                  AR❤: Good night all
1387                          Meena Anni: <Media omitted>
1388          Jambo anna 1: Best servant of the year 2019
1389                        Jambo anna 1: <Media omitted>
Name: 1, Length: 1389, dtype: str

In [17]:
message1 = Message[1].str.split(":", n=1, expand = True)

In [18]:
message1

,0,1
1,"Mama created group ""Happy birthday jambu mama""",NaN
2,Jambo anna 1 added you,NaN
3,Jambo anna 1 changed this group's icon,NaN
4,Mama,♥❤
5,"Jambo anna 1 changed the subject from ""Happy ...",NaN
...,...,...
1385,Meena Anni,Good night all
1386,AR❤,Good night all
1387,Meena Anni,<Media omitted>
1388,Jambo anna 1,Best servant of the year 2019
1389,Jambo anna 1,<Media omitted>

In [19]:
df["Name"] = message1[0]

In [20]:
df

,Date,Chat,Time,Name
1,06/02/17,"10:44 pm - Mama created group ""Happy birthday...",10:44 pm,"Mama created group ""Happy birthday jambu mama"""
2,14/07/19,12:50 pm - Jambo anna 1 added you,12:50 pm,Jambo anna 1 added you
3,14/07/19,12:50 pm - Jambo anna 1 changed this group's ...,12:50 pm,Jambo anna 1 changed this group's icon
4,14/07/19,12:51 pm - Mama: ♥❤,12:51 pm,Mama
5,14/07/19,12:53 pm - Jambo anna 1 changed the subject f...,12:53 pm,"Jambo anna 1 changed the subject from ""Happy ..."
...,...,...,...,...
1385,15/12/19,11:08 pm - Meena Anni: Good night all,11:08 pm,Meena Anni
1386,15/12/19,11:56 pm - AR❤: Good night all,11:56 pm,AR❤
1387,15/12/19,11:58 pm - Meena Anni: <Media omitted>,11:58 pm,Meena Anni
1388,17/12/19,6:52 pm - Jambo anna 1: Best servant of the y...,6:52 pm,Jambo anna 1
1389,17/12/19,6:52 pm - Jambo anna 1: <Media omitted>,6:52 pm,Jambo anna 1

In [22]:
df = df.drop("Chat", axis=1)

In [23]:
df

          Date        Time                                               Name
1     06/02/17   10:44 pm      Mama created group "Happy birthday jambu mama"
2     14/07/19   12:50 pm                              Jambo anna 1 added you
3     14/07/19   12:50 pm              Jambo anna 1 changed this group's icon
4     14/07/19   12:51 pm                                                Mama
5     14/07/19   12:53 pm    Jambo anna 1 changed the subject from "Happy ...
...        ...         ...                                                ...
1385  15/12/19   11:08 pm                                          Meena Anni
1386  15/12/19   11:56 pm                                                 AR❤
1387  15/12/19   11:58 pm                                          Meena Anni
1388  17/12/19    6:52 pm                                        Jambo anna 1
1389  17/12/19    6:52 pm                                        Jambo anna 1

[1389 rows x 3 columns]

In [24]:
df["Chat"] = message1[1]

In [25]:
df

,Date,Time,Name,Chat
1,06/02/17,10:44 pm,"Mama created group ""Happy birthday jambu mama""",NaN
2,14/07/19,12:50 pm,Jambo anna 1 added you,NaN
3,14/07/19,12:50 pm,Jambo anna 1 changed this group's icon,NaN
4,14/07/19,12:51 pm,Mama,♥❤
5,14/07/19,12:53 pm,"Jambo anna 1 changed the subject from ""Happy ...",NaN
...,...,...,...,...
1385,15/12/19,11:08 pm,Meena Anni,Good night all
1386,15/12/19,11:56 pm,AR❤,Good night all
1387,15/12/19,11:58 pm,Meena Anni,<Media omitted>
1388,17/12/19,6:52 pm,Jambo anna 1,Best servant of the year 2019
1389,17/12/19,6:52 pm,Jambo anna 1,<Media omitted>

In [26]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [27]:
dataset.dropna(inplace = True)

In [28]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to C:\Users\Gayathri
[nltk_data]     R\AppData\Roaming\nltk_data...

True

In [29]:
sia = SentimentIntensityAnalyzer()

In [30]:
senti = sia.polarity_scores(df["Chat"][49])

In [31]:
senti

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}