In [2]:
import pandas as pd

In [3]:

import pandas as pd

dataset = pd.read_csv(
    r"C:\Users\fazil\OneDrive\Documents\AI\NLP\Whatsapp chat\input\mabel.txt",
    header=None,
    on_bad_lines='skip',
    encoding='utf-8'
)

In [4]:
dataset

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [6]:
df = dataset.drop(0)

In [7]:
 df

           0                                                  1
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [8]:
df.columns = ["Date", "Chat"]

In [9]:
df

        Date                                               Chat
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [10]:
Message = df["Chat"].str.split("-", n=1, expand = True)

In [11]:
Message

             0                                                  1
1     1:42 pm     Mabel Infoziant: Hi this is Mabel we just spoke
2     1:42 pm              Mabel Infoziant: What’s your full name
3     1:42 pm                                 AR❤: Ramisha Rani K
4     1:42 pm                                 Mabel Infoziant: Ok
5     1:42 pm             Mabel Infoziant: ramisharanik@gmail.com
6     1:43 pm                     Mabel Infoziant: Your email Id?
7     1:43 pm                                        AR❤: Yes Mam
8     1:43 pm    Mabel Infoziant: I will send 2 abstracts for ...
9     1:43 pm                                       AR❤: Yeah mam
10    1:43 pm    Mabel Infoziant: Give me the list that u have...
11    1:43 pm    Mabel Infoziant: Send me cbe office address a...
12    1:44 pm    AR❤: Yeah Mam within Evening I will forward y...
13    1:45 pm    AR❤: Tomorrow I have to visit the office.yet ...
14    1:48 pm                                 Mabel Infoziant: ok
15    1:48 pm    Mabel Infoziant: send the details of office l...
16    1:49 pm    AR❤: Sure mam. Soon I will share details with...
17    2:00 pm    AR❤: I have read the Abstract mam. We can do ...
18    2:04 pm    Mabel Infoziant: I think Vignesh has the data...
19    2:04 pm          Mabel Infoziant: I have sent the abstracts
20    2:06 pm                                         AR❤: Ok mam
21    2:07 pm    AR❤: I have read both the abstract mam. We ca...
22    4:44 pm    Mabel Infoziant: Yes we need to ya about amou...
23    4:48 pm                                      AR❤: Sure mam.
24    8:07 pm                              AR❤: Shall I call mam?
25   10:45 pm    Mabel Infoziant: Hi I was at church couldn’t ...
26   11:52 pm                                     AR❤: It's k mam
27   11:55 pm    AR❤: Just to know the tomorrow plan mam.will ...
28   12:09 pm                AR❤: Mam can u send Vignesh number??
29   12:13 pm    Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30   12:23 pm           Mabel Infoziant: I was in a meeting sorry
31   12:25 pm                                AR❤: Can I cal u mam
32   12:26 pm    AR❤: Waiting for u r finalization of rates fo...
33   12:26 pm    AR❤: If we finiliaze I can work with full inv...
34   12:28 pm    AR❤: So what ever may be ..if you think your ...
35   12:28 pm                       AR❤: You deleted this message
36   12:29 pm                                 AR❤: Do the needful
37   12:41 pm    Mabel Infoziant: No ma please hold I am in a ...
38   12:42 pm                                 AR❤: Ok mam thank u
39    7:59 am    Mabel Infoziant: Ramisha we need to talk toda...
40    8:00 am    Mabel Infoziant: Be ready to discuss about th...
41    8:55 am                                       AR❤: Okay mam
42    2:26 pm                                 Mabel Infoziant: ok
43    8:22 pm                                AR❤: Mam are u free?
44    8:40 pm    Mabel Infoziant: Am at church can call very l...
45    8:40 pm    AR❤: Kk mam. I will ask Arun brother. Small d...
46    3:09 pm                                         AR❤: Hi mam
47    3:09 pm                               AR❤: Any updates mam?
48    3:11 pm    Mabel Infoziant: U might have to start on the...
49    3:11 pm    Mabel Infoziant: There is one project that go...
50    3:12 pm                                       AR❤: Kk mam👍🏻

In [13]:
df["Time"] = Message[0]

In [14]:
df

        Date                                               Chat        Time
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...    1:42 pm
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name    1:42 pm
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K    1:42 pm
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok    1:42 pm
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...    1:42 pm
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?    1:43 pm
7   05/12/19                             1:43 pm - AR❤: Yes Mam    1:43 pm
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...    1:43 pm
9   05/12/19                            1:43 pm - AR❤: Yeah mam    1:43 pm
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...    1:43 pm
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...    1:43 pm
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...    1:44 pm
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...    1:45 pm
14  05/12/19                      1:48 pm - Mabel Infoziant: ok    1:48 pm
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...    1:48 pm
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...    1:49 pm
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...    2:00 pm
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...    2:04 pm
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...    2:04 pm
20  05/12/19                              2:06 pm - AR❤: Ok mam    2:06 pm
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...    2:07 pm
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...    4:44 pm
23  05/12/19                           4:48 pm - AR❤: Sure mam.    4:48 pm
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?    8:07 pm
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...   10:45 pm
26  08/12/19                         11:52 pm - AR❤: It's k mam   11:52 pm
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...   11:55 pm
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??   12:09 pm
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...   12:13 pm
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...   12:23 pm
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam   12:25 pm
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...   12:26 pm
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...   12:26 pm
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...   12:28 pm
35  09/12/19           12:28 pm - AR❤: You deleted this message   12:28 pm
36  09/12/19                     12:29 pm - AR❤: Do the needful   12:29 pm
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...   12:41 pm
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u   12:42 pm
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...    7:59 am
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...    8:00 am
41  10/12/19                            8:55 am - AR❤: Okay mam    8:55 am
42  12/12/19                      2:26 pm - Mabel Infoziant: ok    2:26 pm
43  15/12/19                     8:22 pm - AR❤: Mam are u free?    8:22 pm
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...    8:40 pm
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...    8:40 pm
46  18/12/19                              3:09 pm - AR❤: Hi mam    3:09 pm
47  18/12/19                    3:09 pm - AR❤: Any updates mam?    3:09 pm
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...    3:11 pm
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...    3:11 pm
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻    3:12 pm

In [15]:
Message[1]

1       Mabel Infoziant: Hi this is Mabel we just spoke
2                Mabel Infoziant: What’s your full name
3                                   AR❤: Ramisha Rani K
4                                   Mabel Infoziant: Ok
5               Mabel Infoziant: ramisharanik@gmail.com
6                       Mabel Infoziant: Your email Id?
7                                          AR❤: Yes Mam
8      Mabel Infoziant: I will send 2 abstracts for ...
9                                         AR❤: Yeah mam
10     Mabel Infoziant: Give me the list that u have...
11     Mabel Infoziant: Send me cbe office address a...
12     AR❤: Yeah Mam within Evening I will forward y...
13     AR❤: Tomorrow I have to visit the office.yet ...
14                                  Mabel Infoziant: ok
15     Mabel Infoziant: send the details of office l...
16     AR❤: Sure mam. Soon I will share details with...
17     AR❤: I have read the Abstract mam. We can do ...
18     Mabel Infoziant: I think Vignesh has the data...
19           Mabel Infoziant: I have sent the abstracts
20                                          AR❤: Ok mam
21     AR❤: I have read both the abstract mam. We ca...
22     Mabel Infoziant: Yes we need to ya about amou...
23                                       AR❤: Sure mam.
24                               AR❤: Shall I call mam?
25     Mabel Infoziant: Hi I was at church couldn’t ...
26                                      AR❤: It's k mam
27     AR❤: Just to know the tomorrow plan mam.will ...
28                 AR❤: Mam can u send Vignesh number??
29     Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30            Mabel Infoziant: I was in a meeting sorry
31                                 AR❤: Can I cal u mam
32     AR❤: Waiting for u r finalization of rates fo...
33     AR❤: If we finiliaze I can work with full inv...
34     AR❤: So what ever may be ..if you think your ...
35                        AR❤: You deleted this message
36                                  AR❤: Do the needful
37     Mabel Infoziant: No ma please hold I am in a ...
38                                  AR❤: Ok mam thank u
39     Mabel Infoziant: Ramisha we need to talk toda...
40     Mabel Infoziant: Be ready to discuss about th...
41                                        AR❤: Okay mam
42                                  Mabel Infoziant: ok
43                                 AR❤: Mam are u free?
44     Mabel Infoziant: Am at church can call very l...
45     AR❤: Kk mam. I will ask Arun brother. Small d...
46                                          AR❤: Hi mam
47                                AR❤: Any updates mam?
48     Mabel Infoziant: U might have to start on the...
49     Mabel Infoziant: There is one project that go...
50                                        AR❤: Kk mam👍🏻
Name: 1, dtype: object

In [16]:
message1 = Message[1].str.split(":", n=1, expand = True)

In [17]:
message1

                   0                                                  1
1    Mabel Infoziant                     Hi this is Mabel we just spoke
2    Mabel Infoziant                              What’s your full name
3                AR❤                                     Ramisha Rani K
4    Mabel Infoziant                                                 Ok
5    Mabel Infoziant                             ramisharanik@gmail.com
6    Mabel Infoziant                                     Your email Id?
7                AR❤                                            Yes Mam
8    Mabel Infoziant     I will send 2 abstracts for u to start working
9                AR❤                                           Yeah mam
10   Mabel Infoziant                   Give me the list that u have too
11   Mabel Infoziant   Send me cbe office address and phone number I...
12               AR❤    Yeah Mam within Evening I will forward you mam.
13               AR❤   Tomorrow I have to visit the office.yet not I...
14   Mabel Infoziant                                                 ok
15   Mabel Infoziant   send the details of office location once u ge...
16               AR❤   Sure mam. Soon I will share details with you mam
17               AR❤   I have read the Abstract mam. We can do mam. ...
18   Mabel Infoziant   I think Vignesh has the data set will ask him...
19   Mabel Infoziant                          I have sent the abstracts
20               AR❤                                             Ok mam
21               AR❤   I have read both the abstract mam. We can do ...
22   Mabel Infoziant   Yes we need to ya about amount and all other ...
23               AR❤                                          Sure mam.
24               AR❤                                  Shall I call mam?
25   Mabel Infoziant         Hi I was at church couldn’t take your call
26               AR❤                                         It's k mam
27               AR❤   Just to know the tomorrow plan mam.will see t...
28               AR❤                    Mam can u send Vignesh number??
29   Mabel Infoziant           Vignesh ML Infoziant.vcf (file attached)
30   Mabel Infoziant                           I was in a meeting sorry
31               AR❤                                    Can I cal u mam
32               AR❤   Waiting for u r finalization of rates for our...
33               AR❤   If we finiliaze I can work with full involvem...
34               AR❤   So what ever may be ..if you think your are c...
35               AR❤                           You deleted this message
36               AR❤                                     Do the needful
37   Mabel Infoziant   No ma please hold I am in a hot meeting with ...
38               AR❤                                     Ok mam thank u
39   Mabel Infoziant   Ramisha we need to talk today i will call u a...
40   Mabel Infoziant     Be ready to discuss about the ML titles u have
41               AR❤                                           Okay mam
42   Mabel Infoziant                                                 ok
43               AR❤                                    Mam are u free?
44   Mabel Infoziant   Am at church can call very late or tomorrow only
45               AR❤   Kk mam. I will ask Arun brother. Small doubt ...
46               AR❤                                             Hi mam
47               AR❤                                   Any updates mam?
48   Mabel Infoziant     U might have to start on the WhatsApp analysis
49   Mabel Infoziant            There is one project that got committed
50               AR❤                                           Kk mam👍🏻

In [22]:
df["Name"] = message1[0]

In [23]:
df

,Date,Chat,Time,Name
1,05/12/19,1:42 pm - Mabel Infoziant: Hi this is Mabel w...,1:42 pm,Mabel Infoziant
2,05/12/19,1:42 pm - Mabel Infoziant: What’s your full name,1:42 pm,Mabel Infoziant
3,05/12/19,1:42 pm - AR❤: Ramisha Rani K,1:42 pm,AR❤
4,05/12/19,1:42 pm - Mabel Infoziant: Ok,1:42 pm,Mabel Infoziant
5,05/12/19,1:42 pm - Mabel Infoziant: ramisharanik@gmail...,1:42 pm,Mabel Infoziant
6,05/12/19,1:43 pm - Mabel Infoziant: Your email Id?,1:43 pm,Mabel Infoziant
7,05/12/19,1:43 pm - AR❤: Yes Mam,1:43 pm,AR❤
8,05/12/19,1:43 pm - Mabel Infoziant: I will send 2 abst...,1:43 pm,Mabel Infoziant
9,05/12/19,1:43 pm - AR❤: Yeah mam,1:43 pm,AR❤
10,05/12/19,1:43 pm - Mabel Infoziant: Give me the list t...,1:43 pm,Mabel Infoziant
11,05/12/19,1:43 pm - Mabel Infoziant: Send me cbe office...,1:43 pm,Mabel Infoziant
12,05/12/19,1:44 pm - AR❤: Yeah Mam within Evening I will...,1:44 pm,AR❤
13,05/12/19,1:45 pm - AR❤: Tomorrow I have to visit the o...,1:45 pm,AR❤
14,05/12/19,1:48 pm - Mabel Infoziant: ok,1:48 pm,Mabel Infoziant
15,05/12/19,1:48 pm - Mabel Infoziant: send the details o...,1:48 pm,Mabel Infoziant
16,05/12/19,1:49 pm - AR❤: Sure mam. Soon I will share de...,1:49 pm,AR❤
17,05/12/19,2:00 pm - AR❤: I have read the Abstract mam. ...,2:00 pm,AR❤
18,05/12/19,2:04 pm - Mabel Infoziant: I think Vignesh ha...,2:04 pm,Mabel Infoziant
19,05/12/19,2:04 pm - Mabel Infoziant: I have sent the ab...,2:04 pm,Mabel Infoziant
20,05/12/19,2:06 pm - AR❤: Ok mam,2:06 pm,AR❤
21,05/12/19,2:07 pm - AR❤: I have read both the abstract ...,2:07 pm,AR❤
22,05/12/19,4:44 pm - Mabel Infoziant: Yes we need to ya ...,4:44 pm,Mabel Infoziant
23,05/12/19,4:48 pm - AR❤: Sure mam.,4:48 pm,AR❤
24,05/12/19,8:07 pm - AR❤: Shall I call mam?,8:07 pm,AR❤
25,08/12/19,10:45 pm - Mabel Infoziant: Hi I was at churc...,10:45 pm,Mabel Infoziant
26,08/12/19,11:52 pm - AR❤: It's k mam,11:52 pm,AR❤
27,08/12/19,11:55 pm - AR❤: Just to know the tomorrow pla...,11:55 pm,AR❤
28,09/12/19,12:09 pm - AR❤: Mam can u send Vignesh number??,12:09 pm,AR❤
29,09/12/19,12:13 pm - Mabel Infoziant: Vignesh ML Infozi...,12:13 pm,Mabel Infoziant
30,09/12/19,12:23 pm - Mabel Infoziant: I was in a meetin...,12:23 pm,Mabel Infoziant
31,09/12/19,12:25 pm - AR❤: Can I cal u mam,12:25 pm,AR❤
32,09/12/19,12:26 pm - AR❤: Waiting for u r finalization ...,12:26 pm,AR❤
33,09/12/19,12:26 pm - AR❤: If we finiliaze I can work wi...,12:26 pm,AR❤
34,09/12/19,12:28 pm - AR❤: So what ever may be ..if you ...,12:28 pm,AR❤
35,09/12/19,12:28 pm - AR❤: You deleted this message,12:28 pm,AR❤
36,09/12/19,12:29 pm - AR❤: Do the needful,12:29 pm,AR❤
37,09/12/19,12:41 pm - Mabel Infoziant: No ma please hold...,12:41 pm,Mabel Infoziant
38,09/12/19,12:42 pm - AR❤: Ok mam thank u,12:42 pm,AR❤
39,10/12/19,7:59 am - Mabel Infoziant: Ramisha we need to...,7:59 am,Mabel Infoziant
40,10/12/19,8:00 am - Mabel Infoziant: Be ready to discus...,8:00 am,Mabel Infoziant
41,10/12/19,8:55 am - AR❤: Okay mam,8:55 am,AR❤
42,12/12/19,2:26 pm - Mabel Infoziant: ok,2:26 pm,Mabel Infoziant
43,15/12/19,8:22 pm - AR❤: Mam are u free?,8:22 pm,AR❤
44,15/12/19,8:40 pm - Mabel Infoziant: Am at church can c...,8:40 pm,Mabel Infoziant
45,15/12/19,8:40 pm - AR❤: Kk mam. I will ask Arun brothe...,8:40 pm,AR❤
46,18/12/19,3:09 pm - AR❤: Hi mam,3:09 pm,AR❤
47,18/12/19,3:09 pm - AR❤: Any updates mam?,3:09 pm,AR❤
48,18/12/19,3:11 pm - Mabel Infoziant: U might have to st...,3:11 pm,Mabel Infoziant
49,18/12/19,3:11 pm - Mabel Infoziant: There is one proje...,3:11 pm,Mabel Infoziant
50,18/12/19,3:12 pm - AR❤: Kk mam👍🏻,3:12 pm,AR❤

In [24]:
df = df.drop(columns = "Chat", axis = 1)

In [25]:
df

        Date        Time              Name
1   05/12/19    1:42 pm    Mabel Infoziant
2   05/12/19    1:42 pm    Mabel Infoziant
3   05/12/19    1:42 pm                AR❤
4   05/12/19    1:42 pm    Mabel Infoziant
5   05/12/19    1:42 pm    Mabel Infoziant
6   05/12/19    1:43 pm    Mabel Infoziant
7   05/12/19    1:43 pm                AR❤
8   05/12/19    1:43 pm    Mabel Infoziant
9   05/12/19    1:43 pm                AR❤
10  05/12/19    1:43 pm    Mabel Infoziant
11  05/12/19    1:43 pm    Mabel Infoziant
12  05/12/19    1:44 pm                AR❤
13  05/12/19    1:45 pm                AR❤
14  05/12/19    1:48 pm    Mabel Infoziant
15  05/12/19    1:48 pm    Mabel Infoziant
16  05/12/19    1:49 pm                AR❤
17  05/12/19    2:00 pm                AR❤
18  05/12/19    2:04 pm    Mabel Infoziant
19  05/12/19    2:04 pm    Mabel Infoziant
20  05/12/19    2:06 pm                AR❤
21  05/12/19    2:07 pm                AR❤
22  05/12/19    4:44 pm    Mabel Infoziant
23  05/12/19    4:48 pm                AR❤
24  05/12/19    8:07 pm                AR❤
25  08/12/19   10:45 pm    Mabel Infoziant
26  08/12/19   11:52 pm                AR❤
27  08/12/19   11:55 pm                AR❤
28  09/12/19   12:09 pm                AR❤
29  09/12/19   12:13 pm    Mabel Infoziant
30  09/12/19   12:23 pm    Mabel Infoziant
31  09/12/19   12:25 pm                AR❤
32  09/12/19   12:26 pm                AR❤
33  09/12/19   12:26 pm                AR❤
34  09/12/19   12:28 pm                AR❤
35  09/12/19   12:28 pm                AR❤
36  09/12/19   12:29 pm                AR❤
37  09/12/19   12:41 pm    Mabel Infoziant
38  09/12/19   12:42 pm                AR❤
39  10/12/19    7:59 am    Mabel Infoziant
40  10/12/19    8:00 am    Mabel Infoziant
41  10/12/19    8:55 am                AR❤
42  12/12/19    2:26 pm    Mabel Infoziant
43  15/12/19    8:22 pm                AR❤
44  15/12/19    8:40 pm    Mabel Infoziant
45  15/12/19    8:40 pm                AR❤
46  18/12/19    3:09 pm                AR❤
47  18/12/19    3:09 pm                AR❤
48  18/12/19    3:11 pm    Mabel Infoziant
49  18/12/19    3:11 pm    Mabel Infoziant
50  18/12/19    3:12 pm                AR❤

In [26]:
df["Chat"] = message1[1]

In [27]:
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [34]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [30]:
dataset.dropna(inplace = True)

In [35]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\fazil\AppData\Roaming\nltk_data...

True

In [38]:
sia = SentimentIntensityAnalyzer()

In [53]:
seti = sia.polarity_scores(df["Chat"][49])

In [54]:
seti

{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'compound': 0.2732}